runtime: python39  
entrypoint: gunicorn -b :$PORT main:app'  
instance_class: F2  
env_variables:
  UPLOAD_FOLDER: "app/uploads"

handlers:
  # Serve static files
  - url: /static
    static_dir: app/static

  # Serve uploads 
  - url: /uploads
    static_dir: app/uploads

  - url: /.*
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5